language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

install:
#  - git clone --branch=master https://gist.github.com/eded9f462abdfee52262f98fa7583c23.git ./oscript-install
  - pwd
  - git clone -q --branch=master https://github.com/artbear/OneScript-install.git ./oscript-install
  - chmod +x ./oscript-install/install.sh
  - sudo ./oscript-install/install.sh
  - rm -rf ./oscript-install
  - echo "Installation 1 complete"
  - which oscript
  - oscript -version
  - sudo opm install opm
  - sudo opm install 1testrunner

script:
 - echo "Running tests"
 - oscript -encoding=utf-8 main.os -runall tests xddReportPath tests

sudo: required

os:
  - linux